### PR TITLE
Updated it translations

### PR DESCRIPTION
**Pull request by jpaniagualaconich**
Updated Italian translations.

## Description

Fixed minor errors (missing or extra periods), unified terms and added missing translations for both `example` and `two_factor`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jpaniagualaconich** [comment]
I see this is managed through transifex. How would that work? Would it be something like: get them reviewed, get permission to tx-push?

**Comment by claudep** [comment]
Indeed, you should translate on Transifex, and translations will get integrated on next release.

**Comment by jpaniagualaconich** [comment]
Thanks for the prompt reply! Transifex newbie here.

Would it be possible for me to tx-push?
I would like to avoid going through the point and click interface, translating things one by one.
Or perhaps there's a third option I've yet to discover?

**Comment by jpaniagualaconich** [comment]
Oh, silly me!
I understood the problem now and tx-pushed.
Thanks again.

**Pull request closed without merging**
