### PR TITLE
Store the user's password hash in the session rather than plain text

### LINKED ISSUE #239: Passwords are stored in plain-text in the user's session
When using the login wizard the user's password is stored in plain text in the session store. The information is stored by formtools' wizard class. This is a security risk, depending on the deployment this can easily lead to a leak. Imagine a shared database ...

The information is not required to complete the token step, it would suffice to store the authentication state once the user's username and password are verified and then call `login()` in the `done()` method.

### PR DESCRIPTION
**Pull request by thecardcheat**
## Description

This maintains the current behavior of allowing the wizard to re-validate the auth form but keeps the user's password out of the session.

## Motivation and Context

This is a more straightforward solution than either #193 or #194 and should close #239 and #221. It's possible that certain configurations may not want to allow the password hash into the session either, but in many cases the level of access to the table with password hashes will match those with access to the session and it is still much more secure than allowing the plain text password to persist at all.

## How Has This Been Tested?

Ran tox suite and tested in a local project.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Bouke** [comment]
This assumes a `password` field on the user model, which I think is not a mandatory field on a [`CustomUser`](https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#django.contrib.auth.models.CustomUser). An application might be backed by LDAP for instance, so the password is stored external to this application. 

Also I'm a bit wary as this adds a custom authentication form and custom authentication logic, which might not have received the same scrutiny as Django's built-in login form. (I'm aware that the same argument also holds for this library itself.)

**Comment by thecardcheat** [comment]
I figured non-PW back-ends would need to provide their own Form anyway since `django.contrib.auth.forms.AuthenticationForm` is just a password auth form, but I can see with this course better checking of the form type would need to be properly handled in `get_form_step_data()`.

I think the form is fine as-is since you'd have to provide one that matches your auth otherwise, but I have never used a non-PW auth back-end in Django.

> I'm a bit wary as this adds a custom authentication form and custom authentication logic, which might not have received the same scrutiny as Django's built-in login form. (I'm aware that the same argument also holds for this library itself.)

That's fair but I think it is worth the maintainability burden because saving the password in plain-text is a deal-breaker for a lot of projects, since it transiently defeats the purpose of using a strong hash, and does so when using an app you'd expect to be increasing security. Implementation-wise it's straightforward and follows the existing `AuthenticationForm` form as closely as possible.

**Comment by Bouke** [comment]
> I figured non-PW back-ends would need to provide their own Form anyway since `django.contrib.auth.forms.AuthenticationForm` is just a password auth form, but I can see with this course better checking of the form type would need to be properly handled in get_form_step_data().

I suspect that custom authentication backends can just piggy-back on the default authentication form. It isn't directly tied to the database layer, but calls `authenticate` instead:

https://github.com/django/django/blob/fe99fb860f12c7440752441ef0da37ed65e5bbe3/django/contrib/auth/forms.py#L192

The issue here is not that other authentication backends might not be expecting a password, but the current implementation that (a) expects the user accounts to be stored in the local database and (b) expects a field called "password" that contains the password hash in a certain encoding. This will cause problems for users of this library that have a custom password validation backend.

**Comment by anlutro** [comment]
Maybe make this an opt-in feature through a setting, for those that do have a local users database and can store the hash like this?

**Comment by moggers87** [comment]
Closing this as this issue has been fixed in 1.12.0

**Pull request closed without merging**
