### PR TITLE
Add testing for Django 3.0

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by moggers87** [comment]
Thanks @claudep :tada:

**Comment by claudep** [comment]
I'm sorry, I just noticed that I forgot adding the `'Framework :: Django :: 3.0',` line in `setup.py`, and mention 3.0 in the README. @moggers87, could you just commit that, or would a like a PR?

**Comment by moggers87** [comment]
It'd need a PR as I can't commit directly to master

**Comment by claudep** [comment]
Done in #325.

**Pull request merged**
