### PR TITLE
Check if prefix exists in session before trying to reset storage

### PR DESCRIPTION
**Pull request by vvojvoda**
This pull request addresses the error which occurs when attempting to login a user while another user is already logged in.
This problem is described in issue #102.

### CODE REVIEW

**Comment by Bouke** [comment]
Could you also come up with a unit test for this fix? So that future changes will not introduce regressions with respect to this bug. Thanks.

**Comment by vvojvoda** [comment]
Thanks for the review. Added a test.

**Comment by vvojvoda** [comment]
@Bouke Do you think this is good to be merged?

**Comment by Bouke** [comment]
Do you know why the check in [``SessionStorage.__init__``][1] doesn't work?

[1]: https://github.com/django/django-formtools/blob/b11c4375ec3a39c6cd5a5509cb8697936dfc5f50/formtools/wizard/storage/session.py#L8

**Pull request merged**
